### ISSUE TITLE
No module named 'flowutilspd'

### ISSUE THREAD

**Issue by md716alam** [burtonrj/CytoPy#6]
I got below error while using this library "from CytoPy.flow.supervised.ref import calculate_ref_sample_fast",

Traceback (most recent call last):
  File "CytoZoetis.py", line 4, in <module>
    from CytoPy.flow.supervised.ref import calculate_ref_sample_fast
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\cytopy-0.0.1-py3.7.egg\CytoPy\flow\supervised\ref.py", line 2, in <module>
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto\lib\site-packages\cytopy-0.0.1-py3.7.egg\CytoPy\flow\transforms.py", line 1, in <module>
ModuleNotFoundError: No module named 'flowutilspd'

**Comment by burtonrj** [comment]
Good morning,

Apologies that you have encountered further issues. This is in relation to the setup issues you experienced previously: #5 

I'm working on a new release to deal with the setup issues encountered. I'm also looking to revert to the "flowutils" module as opposed to the adapted module "flowutilspd" I created for handling pandas dataframes. 

For the time being, please install FlowUtilsPandas in your local environment by downloading the repository from here:
https://github.com/burtonrj/FlowUtilsPandas

Once you have downloaded this, navigate to the folder and run `pip install .` this should solve the issues you are having.

**Comment by md716alam** [comment]
Hi ,
I have installed FlowUtilsPanads package , but one more error coming .
Traceback (most recent call last):
  File "CytoZoetis.py", line 4, in <module>
    from CytoPy.flow.supervised.ref import calculate_ref_sample_fast
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\zoetis\lib\site-packages\CytoPy\flow\supervised\ref.py", line 2, in <module>        
    from ..transforms import apply_transform
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\zoetis\lib\site-packages\CytoPy\flow\transforms.py", line 2, in <module>
    from .supervised.utilities import scaler
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\zoetis\lib\site-packages\CytoPy\flow\supervised\utilities.py", line 3, in <module>  
    from ..gating.actions import Gating
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\zoetis\lib\site-packages\CytoPy\flow\gating\actions.py", line 7, in <module>        
    from ..transforms import apply_transform
ImportError: cannot import name 'apply_transform' from 'CytoPy.flow.transforms' (C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\zoetis\lib\site-packages\CytoPy\flow\transforms.py)

**Comment by burtonrj** [comment]
Hi,

So it seems a change I had made on a local branch I had accidentally committed to the master branch. I've corrected this so you shouldn't get import conflicts in CytoPy.flow.transforms now. Sorry about this. You will need to uninstall CytoPy and reinstall as per the install instructions in the readme.

**Comment by md716alam** [comment]
Hi,
I created new environment using anaconda and installed cytopy using " pip install git+https://github.com/burtonrj/CytoPy.git"
then i got error,,,,,,,,
ModuleNotFoundError: No module named 'flowutilspd'
then i installed  FlowUtilsPandas using git+https://github.com/burtonrj/FlowUtilsPandas
After installing FlowUtilsPandas i tried to run cyto code then again got below error.

Please help me to run cyto code.
### Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\tauala\\AppData\\Local\\Continuum\\anaconda3\\envs\\cyto_z\\Library\\lib\\geos_c.dll'].
.................................................error.....................................................................................................................
_Traceback (most recent call last):
  File "CytoZoetis.py", line 4, in <module>
    from CytoPy.flow.supervised.ref import calculate_ref_sample_fast
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\CytoPy\flow\supervised\ref.py", line 3, in <module>        
    from .utilities import find_common_features
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\CytoPy\flow\supervised\utilities.py", line 3, in <module>  
    from ..gating.actions import Gating
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\CytoPy\flow\gating\actions.py", line 8, in <module>        
    from .base import GateError
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\CytoPy\flow\gating\base.py", line 3, in <module>
    from .utilities import density_dependent_downsample
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\CytoPy\flow\gating\utilities.py", line 1, in <module>      
    from shapely.geometry import Point, Polygon
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\shapely\geometry\base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\shapely\geos.py", line 130, in <module>
    os.path.join(sys.prefix, "Library", "lib", "geos_c.dll"),
  File "C:\Users\tauala\AppData\Local\Continuum\anaconda3\envs\cyto_z\lib\site-packages\shapely\geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\tauala\\AppData\\Local\\Continuum\\anaconda3\\envs\\cyto_z\\Library\\lib\\geos_c.dll']._

**Comment by burtonrj** [comment]
This is the same Anaconda issue as addressed in #5, please run the following in your anaconda environment:

`conda install -c conda-forge shapely`

For future readers, until a future release of CytoPy is published (>0.0.1) I would recommend using base Python and not Anaconda. You can use VirtualEnvironment with base Python. A good tutorial here: https://realpython.com/python-virtual-environments-a-primer/

**Comment by md716alam** [comment]
Hi, 
Now I am started using pip instead of conda and i have installed cytopy but there are some error still coming ,
If below error is related to shapely then what comand should use instead of _conda install -c conda-forge shapely__
because now using pip so cannot use conda anymore .
Traceback (most recent call last):
  File "CytoZoetis.py", line 4, in <module>
    from CytoPy.flow.supervised.ref import calculate_ref_sample_fast
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\CytoPy\flow\supervised\ref.py", line 3, in <module>
    from .utilities import find_common_features
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\CytoPy\flow\supervised\utilities.py", line 3, in <module>
    from ..gating.actions import Gating
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\CytoPy\flow\gating\actions.py", line 8, in <module>
    from .base import GateError
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\CytoPy\flow\gating\base.py", line 3, in <module>
    from .utilities import density_dependent_downsample
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\CytoPy\flow\gating\utilities.py", line 1, in <module>
    from shapely.geometry import Point, Polygon
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\shapely\geometry\__init__.py", line 4, in <module>
    from .base import CAP_STYLE, JOIN_STYLE
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\shapely\geometry\base.py", line 17, in <module>
    from shapely.coords import CoordinateSequence
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\shapely\coords.py", line 8, in <module>
    from shapely.geos import lgeos
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\shapely\geos.py", line 130, in <module>
    os.path.join(sys.prefix, "Library", "lib", "geos_c.dll"),
  File "C:\Users\tauala\Desktop\Projects\cyto_env\lib\site-packages\shapely\geos.py", line 56, in load_dll
    libname, fallbacks or []))
OSError: Could not find lib geos_c.dll or load any of its variants ['C:\\Users\\tauala\\Desktop\\Projects\\cyto_env\\Library\\lib\\geos_c.dll'].

**Comment by burtonrj** [comment]
Shapely is listed on PyPi so install shapely like so:

`pip install shapely`

**Comment by md716alam** [comment]
I have already used _pip install shapely_ and even it is installed ,
the issue is coming because of this  _from CytoPy.flow.supervised.ref import calculate_ref_sample_fast_
you can check above error.

**Comment by md716alam** [comment]
I have already used _pip install shapely_ and even it is installed ,
the issue is coming because of this  _from CytoPy.flow.supervised.ref import calculate_ref_sample_fast_
you can check above error.

**Comment by burtonrj** [comment]
No, if you inspect the error stack you can see that when this import is made, `from shapely.geometry import Point, Polygon`, an error is thrown. This issue is arising from your `shapely` install not from CytoPy. Try looking at similar issues: https://tinyurl.com/y8md6rf5

I'm closing this thread since it's an issues with shapely and not directly a CytoPy issue.
